/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Inscription (void);
GtkWidget* create_Interfaceclient (void);
GtkWidget* create_InterfaceAgent (void);
GtkWidget* create_InterfaceAdmin (void);
GtkWidget* create_user (void);
GtkWidget* create_gestion_des_cients (void);
GtkWidget* create_window2 (void);
GtkWidget* create_dialog1 (void);
GtkWidget* create_window3 (void);
