/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *eventbox1;
  GtkWidget *alignment1;
  GtkWidget *fixed1;
  GtkWidget *toolitem1;
  GtkWidget *toolitem2;
  GtkWidget *button3;
  GtkWidget *button5;
  GtkWidget *entry1;
  GtkWidget *vseparator1;
  GtkWidget *vseparator2;
  GtkWidget *vseparator6;
  GtkWidget *vseparator9;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *label5;
  GtkWidget *label7;
  GtkWidget *button8;
  GtkWidget *label6;
  GtkWidget *button7;
  GtkWidget *label8;
  GtkWidget *vseparator10;
  GtkWidget *button9;
  GtkWidget *button11;
  GtkWidget *button12;
  GtkWidget *hseparator1;
  GtkWidget *vseparator8;
  GtkWidget *vseparator12;
  GtkWidget *vseparator11;
  GtkWidget *hseparator2;
  GtkWidget *button6;
  GtkWidget *button4;
  GtkWidget *vseparator7;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_container_add (GTK_CONTAINER (window2), eventbox1);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (eventbox1), alignment1);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (alignment1), fixed1);

  toolitem1 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem1);
  gtk_fixed_put (GTK_FIXED (fixed1), toolitem1, 1416, 192);
  gtk_widget_set_size_request (toolitem1, 824, 16);

  toolitem2 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem2);
  gtk_fixed_put (GTK_FIXED (fixed1), toolitem2, 1072, 280);
  gtk_widget_set_size_request (toolitem2, 50, 50);

  button3 = gtk_button_new_with_mnemonic (_("flights"));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed1), button3, 200, 88);
  gtk_widget_set_size_request (button3, 126, 50);

  button5 = gtk_button_new_with_mnemonic (_("Hotels"));
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed1), button5, 584, 88);
  gtk_widget_set_size_request (button5, 126, 50);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 1166, 80);
  gtk_widget_set_size_request (entry1, 221, 45);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_fixed_put (GTK_FIXED (fixed1), vseparator1, 288, 248);
  gtk_widget_set_size_request (vseparator1, 16, 16);

  vseparator2 = gtk_vseparator_new ();
  gtk_widget_show (vseparator2);
  gtk_fixed_put (GTK_FIXED (fixed1), vseparator2, 368, 280);
  gtk_widget_set_size_request (vseparator2, 16, 16);

  vseparator6 = gtk_vseparator_new ();
  gtk_widget_show (vseparator6);
  gtk_fixed_put (GTK_FIXED (fixed1), vseparator6, 552, 240);
  gtk_widget_set_size_request (vseparator6, 16, 16);

  vseparator9 = gtk_vseparator_new ();
  gtk_widget_show (vseparator9);
  gtk_fixed_put (GTK_FIXED (fixed1), vseparator9, 592, 264);
  gtk_widget_set_size_request (vseparator9, 16, 16);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 1176, 256);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed1), entry3, 1176, 312);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  label5 = gtk_label_new (_("Connect"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 1176, 192);
  gtk_widget_set_size_request (label5, 77, 42);
  gtk_label_set_justify (GTK_LABEL (label5), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label5), 0.63, 0.83);
  gtk_misc_set_padding (GTK_MISC (label5), 0, 14);
  gtk_label_set_ellipsize (GTK_LABEL (label5), PANGO_ELLIPSIZE_MIDDLE);

  label7 = gtk_label_new (_("user_name"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed1), label7, 1088, 264);
  gtk_widget_set_size_request (label7, 78, 17);

  button8 = gtk_button_new_with_mnemonic (_("Log in"));
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed1), button8, 1224, 368);
  gtk_widget_set_size_request (button8, 66, 29);

  label6 = gtk_label_new (_("Best Trips"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed1), label6, 64, 152);
  gtk_widget_set_size_request (label6, 105, 53);
  gtk_label_set_justify (GTK_LABEL (label6), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);

  button7 = gtk_button_new_with_mnemonic (_("Recherche"));
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed1), button7, 1032, 80);
  gtk_widget_set_size_request (button7, 0, 48);

  label8 = gtk_label_new (_("Password"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed1), label8, 1088, 320);
  gtk_widget_set_size_request (label8, 83, 16);

  vseparator10 = gtk_vseparator_new ();
  gtk_widget_show (vseparator10);
  gtk_fixed_put (GTK_FIXED (fixed1), vseparator10, 568, 272);
  gtk_widget_set_size_request (vseparator10, 16, 16);

  button9 = gtk_button_new_with_mnemonic (_("Details\n"));
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed1), button9, 56, 424);
  gtk_widget_set_size_request (button9, 66, 29);

  button11 = gtk_button_new_with_mnemonic (_("Details\n"));
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed1), button11, 416, 424);
  gtk_widget_set_size_request (button11, 66, 29);

  button12 = gtk_button_new_with_mnemonic (_("Details\n"));
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed1), button12, 728, 424);
  gtk_widget_set_size_request (button12, 66, 29);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed1), hseparator1, 832, 400);
  gtk_widget_set_size_request (hseparator1, 16, 16);

  vseparator8 = gtk_vseparator_new ();
  gtk_widget_show (vseparator8);
  gtk_fixed_put (GTK_FIXED (fixed1), vseparator8, 600, 758);
  gtk_widget_set_size_request (vseparator8, 0, 262);

  vseparator12 = gtk_vseparator_new ();
  gtk_widget_show (vseparator12);
  gtk_fixed_put (GTK_FIXED (fixed1), vseparator12, 530, 320);
  gtk_widget_set_size_request (vseparator12, 16, 16);

  vseparator11 = gtk_vseparator_new ();
  gtk_widget_show (vseparator11);
  gtk_fixed_put (GTK_FIXED (fixed1), vseparator11, 256, 192);
  gtk_widget_set_size_request (vseparator11, 52, 295);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_fixed_put (GTK_FIXED (fixed1), hseparator2, 636, 200);
  gtk_widget_set_size_request (hseparator2, 16, 16);

  button6 = gtk_button_new_with_mnemonic (_("Cars"));
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed1), button6, 742, 88);
  gtk_widget_set_size_request (button6, 126, 50);

  button4 = gtk_button_new_with_mnemonic (_("Cruises"));
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed1), button4, 424, 88);
  gtk_widget_set_size_request (button4, 126, 50);

  vseparator7 = gtk_vseparator_new ();
  gtk_widget_show (vseparator7);
  gtk_fixed_put (GTK_FIXED (fixed1), vseparator7, 636, 176);
  gtk_widget_set_size_request (vseparator7, 0, 408);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (window2, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window2, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window2, toolitem1, "toolitem1");
  GLADE_HOOKUP_OBJECT (window2, toolitem2, "toolitem2");
  GLADE_HOOKUP_OBJECT (window2, button3, "button3");
  GLADE_HOOKUP_OBJECT (window2, button5, "button5");
  GLADE_HOOKUP_OBJECT (window2, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window2, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (window2, vseparator2, "vseparator2");
  GLADE_HOOKUP_OBJECT (window2, vseparator6, "vseparator6");
  GLADE_HOOKUP_OBJECT (window2, vseparator9, "vseparator9");
  GLADE_HOOKUP_OBJECT (window2, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window2, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window2, label5, "label5");
  GLADE_HOOKUP_OBJECT (window2, label7, "label7");
  GLADE_HOOKUP_OBJECT (window2, button8, "button8");
  GLADE_HOOKUP_OBJECT (window2, label6, "label6");
  GLADE_HOOKUP_OBJECT (window2, button7, "button7");
  GLADE_HOOKUP_OBJECT (window2, label8, "label8");
  GLADE_HOOKUP_OBJECT (window2, vseparator10, "vseparator10");
  GLADE_HOOKUP_OBJECT (window2, button9, "button9");
  GLADE_HOOKUP_OBJECT (window2, button11, "button11");
  GLADE_HOOKUP_OBJECT (window2, button12, "button12");
  GLADE_HOOKUP_OBJECT (window2, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (window2, vseparator8, "vseparator8");
  GLADE_HOOKUP_OBJECT (window2, vseparator12, "vseparator12");
  GLADE_HOOKUP_OBJECT (window2, vseparator11, "vseparator11");
  GLADE_HOOKUP_OBJECT (window2, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (window2, button6, "button6");
  GLADE_HOOKUP_OBJECT (window2, button4, "button4");
  GLADE_HOOKUP_OBJECT (window2, vseparator7, "vseparator7");

  return window2;
}

GtkWidget*
create_fileselection1 (void)
{
  GtkWidget *fileselection1;
  GtkWidget *ok_button2;
  GtkWidget *cancel_button2;

  fileselection1 = gtk_file_selection_new (_("Choisir un fichier"));
  gtk_container_set_border_width (GTK_CONTAINER (fileselection1), 10);
  gtk_window_set_type_hint (GTK_WINDOW (fileselection1), GDK_WINDOW_TYPE_HINT_DIALOG);

  ok_button2 = GTK_FILE_SELECTION (fileselection1)->ok_button;
  gtk_widget_show (ok_button2);
  GTK_WIDGET_SET_FLAGS (ok_button2, GTK_CAN_DEFAULT);

  cancel_button2 = GTK_FILE_SELECTION (fileselection1)->cancel_button;
  gtk_widget_show (cancel_button2);
  GTK_WIDGET_SET_FLAGS (cancel_button2, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fileselection1, fileselection1, "fileselection1");
  GLADE_HOOKUP_OBJECT_NO_REF (fileselection1, ok_button2, "ok_button2");
  GLADE_HOOKUP_OBJECT_NO_REF (fileselection1, cancel_button2, "cancel_button2");

  return fileselection1;
}

GtkWidget*
create_window5 (void)
{
  GtkWidget *window5;
  GtkWidget *fixed2;
  GtkWidget *button15;
  GtkWidget *button16;
  GtkWidget *button17;
  GtkWidget *entry4;
  GtkWidget *button18;
  GtkWidget *button14;
  GtkWidget *label9;
  GtkWidget *textview1;
  GtkWidget *textview2;
  GtkWidget *textview3;
  GtkWidget *button21;
  GtkWidget *vseparator14;
  GtkWidget *button20;
  GtkWidget *button19;
  GtkWidget *vseparator13;
  GtkWidget *button22;
  GtkWidget *button23;
  GtkWidget *button24;
  GtkWidget *label10;

  window5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window5), _("window5"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window5), fixed2);

  button15 = gtk_button_new_with_mnemonic (_("cruises"));
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed2), button15, 106, 16);
  gtk_widget_set_size_request (button15, 74, 29);

  button16 = gtk_button_new_with_mnemonic (_("Hotels"));
  gtk_widget_show (button16);
  gtk_fixed_put (GTK_FIXED (fixed2), button16, 212, 16);
  gtk_widget_set_size_request (button16, 74, 29);

  button17 = gtk_button_new_with_mnemonic (_("Cars"));
  gtk_widget_show (button17);
  gtk_fixed_put (GTK_FIXED (fixed2), button17, 318, 16);
  gtk_widget_set_size_request (button17, 74, 29);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed2), entry4, 530, 16);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  button18 = gtk_button_new_with_mnemonic (_("Recherche"));
  gtk_widget_show (button18);
  gtk_fixed_put (GTK_FIXED (fixed2), button18, 424, 16);
  gtk_widget_set_size_request (button18, 93, 29);

  button14 = gtk_button_new_with_mnemonic (_("Flights"));
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed2), button14, 0, 16);
  gtk_widget_set_size_request (button14, 74, 29);

  label9 = gtk_label_new (_("Best Trips "));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 0, 64);
  gtk_widget_set_size_request (label9, 0, 31);

  textview1 = gtk_text_view_new ();
  gtk_widget_show (textview1);
  gtk_fixed_put (GTK_FIXED (fixed2), textview1, 0, 192);
  gtk_widget_set_size_request (textview1, 148, 106);

  textview2 = gtk_text_view_new ();
  gtk_widget_show (textview2);
  gtk_fixed_put (GTK_FIXED (fixed2), textview2, 318, 192);
  gtk_widget_set_size_request (textview2, 148, 106);

  textview3 = gtk_text_view_new ();
  gtk_widget_show (textview3);
  gtk_fixed_put (GTK_FIXED (fixed2), textview3, 530, 192);
  gtk_widget_set_size_request (textview3, 148, 106);

  button21 = gtk_button_new_with_mnemonic (_("Details"));
  gtk_widget_show (button21);
  gtk_fixed_put (GTK_FIXED (fixed2), button21, 530, 328);
  gtk_widget_set_size_request (button21, 74, 29);

  vseparator14 = gtk_vseparator_new ();
  gtk_widget_show (vseparator14);
  gtk_fixed_put (GTK_FIXED (fixed2), vseparator14, 424, 104);
  gtk_widget_set_size_request (vseparator14, 110, 286);

  button20 = gtk_button_new_with_mnemonic (_("Details"));
  gtk_widget_show (button20);
  gtk_fixed_put (GTK_FIXED (fixed2), button20, 318, 336);
  gtk_widget_set_size_request (button20, 74, 29);

  button19 = gtk_button_new_with_mnemonic (_("Details"));
  gtk_widget_show (button19);
  gtk_fixed_put (GTK_FIXED (fixed2), button19, 0, 328);
  gtk_widget_set_size_request (button19, 74, 29);

  vseparator13 = gtk_vseparator_new ();
  gtk_widget_show (vseparator13);
  gtk_fixed_put (GTK_FIXED (fixed2), vseparator13, 212, 88);
  gtk_widget_set_size_request (vseparator13, 97, 283);

  button22 = gtk_button_new_with_mnemonic (_("gere compte agent"));
  gtk_widget_show (button22);
  gtk_fixed_put (GTK_FIXED (fixed2), button22, 848, 152);
  gtk_widget_set_size_request (button22, 160, 53);

  button23 = gtk_button_new_with_mnemonic (_("gere compte clients"));
  gtk_widget_show (button23);
  gtk_fixed_put (GTK_FIXED (fixed2), button23, 848, 224);
  gtk_widget_set_size_request (button23, 160, 53);

  button24 = gtk_button_new_with_mnemonic (_("Mes E-mails"));
  gtk_widget_show (button24);
  gtk_fixed_put (GTK_FIXED (fixed2), button24, 848, 304);
  gtk_widget_set_size_request (button24, 160, 53);

  label10 = gtk_label_new (_("Pseudo :"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed2), label10, 848, 112);
  gtk_widget_set_size_request (label10, 49, 17);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window5, window5, "window5");
  GLADE_HOOKUP_OBJECT (window5, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window5, button15, "button15");
  GLADE_HOOKUP_OBJECT (window5, button16, "button16");
  GLADE_HOOKUP_OBJECT (window5, button17, "button17");
  GLADE_HOOKUP_OBJECT (window5, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (window5, button18, "button18");
  GLADE_HOOKUP_OBJECT (window5, button14, "button14");
  GLADE_HOOKUP_OBJECT (window5, label9, "label9");
  GLADE_HOOKUP_OBJECT (window5, textview1, "textview1");
  GLADE_HOOKUP_OBJECT (window5, textview2, "textview2");
  GLADE_HOOKUP_OBJECT (window5, textview3, "textview3");
  GLADE_HOOKUP_OBJECT (window5, button21, "button21");
  GLADE_HOOKUP_OBJECT (window5, vseparator14, "vseparator14");
  GLADE_HOOKUP_OBJECT (window5, button20, "button20");
  GLADE_HOOKUP_OBJECT (window5, button19, "button19");
  GLADE_HOOKUP_OBJECT (window5, vseparator13, "vseparator13");
  GLADE_HOOKUP_OBJECT (window5, button22, "button22");
  GLADE_HOOKUP_OBJECT (window5, button23, "button23");
  GLADE_HOOKUP_OBJECT (window5, button24, "button24");
  GLADE_HOOKUP_OBJECT (window5, label10, "label10");

  return window5;
}

GtkWidget*
create_window7 (void)
{
  GtkWidget *window7;
  GtkWidget *fixed4;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *entry8;
  GtkWidget *entry9;
  GtkWidget *entry10;
  GtkWidget *label20;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton2;
  GtkWidget *radiobutton3;
  GtkWidget *label21;
  GtkWidget *radiobutton4;
  GtkWidget *radiobutton5;
  GtkWidget *radiobutton6;
  GtkWidget *entry14;
  GtkWidget *checkbutton1;
  GtkWidget *checkbutton2;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *label31;
  GtkWidget *label30;
  GtkWidget *label34;
  GtkWidget *button29;
  GtkWidget *label29;
  GtkWidget *checkbutton4;
  GtkWidget *label24;
  GtkWidget *label32;
  GtkWidget *label33;
  GtkWidget *label28;
  GtkWidget *checkbutton3;
  GtkWidget *label25;
  GtkWidget *label35;
  GtkWidget *button30;
  GtkWidget *label17;
  GtkWidget *label15;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label16;
  GtkWidget *button25;
  GtkWidget *label23;
  GtkWidget *button26;
  GtkWidget *button27;
  GtkWidget *image1;
  GtkWidget *label22;
  GtkWidget *_;
  GtkWidget *entry15;

  window7 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window7), _("window7"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (window7), fixed4);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed4), entry5, 0, 88);
  gtk_widget_set_size_request (entry5, 136, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed4), entry6, 160, 88);
  gtk_widget_set_size_request (entry6, 128, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed4), entry7, 312, 88);
  gtk_widget_set_size_request (entry7, 136, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed4), entry8, 464, 88);
  gtk_widget_set_size_request (entry8, 136, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed4), entry9, 624, 88);
  gtk_widget_set_size_request (entry9, 128, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed4), entry10, 776, 88);
  gtk_widget_set_size_request (entry10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  label20 = gtk_label_new (_("Stopover"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed4), label20, 0, 152);
  gtk_widget_set_size_request (label20, 106, 18);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Direct "));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton1, 0, 192);
  gtk_widget_set_size_request (radiobutton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("1stopover"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton2, 0, 240);
  gtk_widget_set_size_request (radiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("2stopovers\n"));
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton3, 0, 288);
  gtk_widget_set_size_request (radiobutton3, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  label21 = gtk_label_new (_("Companies"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed4), label21, 0, 336);
  gtk_widget_set_size_request (label21, 104, 16);

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("company1"));
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton4, 0, 368);
  gtk_widget_set_size_request (radiobutton4, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  radiobutton5 = gtk_radio_button_new_with_mnemonic (NULL, _("company2"));
  gtk_widget_show (radiobutton5);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton5, 0, 408);
  gtk_widget_set_size_request (radiobutton5, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5));

  radiobutton6 = gtk_radio_button_new_with_mnemonic (NULL, _("company3"));
  gtk_widget_show (radiobutton6);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton6, 0, 448);
  gtk_widget_set_size_request (radiobutton6, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton6), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton6));

  entry14 = gtk_entry_new ();
  gtk_widget_show (entry14);
  gtk_fixed_put (GTK_FIXED (fixed4), entry14, 928, 288);
  gtk_widget_set_size_request (entry14, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry14), 8226);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("18Th-20h30"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed4), checkbutton1, 336, 200);
  gtk_widget_set_size_request (checkbutton1, 118, 24);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("21h15-23h45"));
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed4), checkbutton2, 336, 240);
  gtk_widget_set_size_request (checkbutton2, 118, 24);

  label26 = gtk_label_new (_("TUN-ORY,company1"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed4), label26, 464, 200);
  gtk_widget_set_size_request (label26, 166, 21);

  label27 = gtk_label_new (_("TUN-ORY,company1"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed4), label27, 464, 240);
  gtk_widget_set_size_request (label27, 166, 21);

  label31 = gtk_label_new (_("2h30 Direct"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed4), label31, 640, 200);
  gtk_widget_set_size_request (label31, 108, 17);

  label30 = gtk_label_new (_("2h30 Direct"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed4), label30, 640, 240);
  gtk_widget_set_size_request (label30, 108, 17);

  label34 = gtk_label_new (_("4 05 TND"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed4), label34, 760, 200);
  gtk_widget_set_size_request (label34, 90, 17);

  button29 = gtk_button_new_with_mnemonic (_("Reserver"));
  gtk_widget_show (button29);
  gtk_fixed_put (GTK_FIXED (fixed4), button29, 768, 256);
  gtk_widget_set_size_request (button29, 74, 29);

  label29 = gtk_label_new (_("TUN-ORY,company2"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed4), label29, 464, 384);
  gtk_widget_set_size_request (label29, 166, 21);

  checkbutton4 = gtk_check_button_new_with_mnemonic (_("21h15-23h45"));
  gtk_widget_show (checkbutton4);
  gtk_fixed_put (GTK_FIXED (fixed4), checkbutton4, 336, 384);
  gtk_widget_set_size_request (checkbutton4, 118, 24);

  label24 = gtk_label_new (_("company1"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed4), label24, 224, 224);
  gtk_widget_set_size_request (label24, 115, 18);

  label32 = gtk_label_new (_("2h30 Direct"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed4), label32, 640, 344);
  gtk_widget_set_size_request (label32, 108, 17);

  label33 = gtk_label_new (_("2h30 Direct"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed4), label33, 640, 384);
  gtk_widget_set_size_request (label33, 108, 17);

  label28 = gtk_label_new (_("TUN-ORY,company2"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed4), label28, 464, 344);
  gtk_widget_set_size_request (label28, 166, 21);

  checkbutton3 = gtk_check_button_new_with_mnemonic (_("18Th-20h30"));
  gtk_widget_show (checkbutton3);
  gtk_fixed_put (GTK_FIXED (fixed4), checkbutton3, 336, 344);
  gtk_widget_set_size_request (checkbutton3, 118, 24);

  label25 = gtk_label_new (_("company2"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed4), label25, 232, 368);
  gtk_widget_set_size_request (label25, 87, 17);

  label35 = gtk_label_new (_("4 05 TND"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed4), label35, 760, 344);
  gtk_widget_set_size_request (label35, 90, 17);

  button30 = gtk_button_new_with_mnemonic (_("Reserver"));
  gtk_widget_show (button30);
  gtk_fixed_put (GTK_FIXED (fixed4), button30, 768, 408);
  gtk_widget_set_size_request (button30, 74, 29);

  label17 = gtk_label_new (_("ville d'ariv\303\251e"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed4), label17, 160, 64);
  gtk_widget_set_size_request (label17, 126, 16);

  label15 = gtk_label_new (_("ville de depart"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed4), label15, 0, 64);
  gtk_widget_set_size_request (label15, 116, 17);

  label18 = gtk_label_new (_("Date depart "));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed4), label18, 312, 64);
  gtk_widget_set_size_request (label18, 81, 17);

  label19 = gtk_label_new (_("Date Retour "));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed4), label19, 464, 64);
  gtk_widget_set_size_request (label19, 81, 17);

  label16 = gtk_label_new (_("Nombre de voyageur"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed4), label16, 608, 64);
  gtk_widget_set_size_request (label16, 152, 16);

  button25 = gtk_button_new_with_mnemonic (_("Recherche "));
  gtk_widget_show (button25);
  gtk_fixed_put (GTK_FIXED (fixed4), button25, 944, 80);
  gtk_widget_set_size_request (button25, 99, 32);

  label23 = gtk_label_new (_("Pseudo "));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed4), label23, 960, 264);
  gtk_widget_set_size_request (label23, 86, 17);

  button26 = gtk_button_new_with_mnemonic (_("gere compte "));
  gtk_widget_show (button26);
  gtk_fixed_put (GTK_FIXED (fixed4), button26, 928, 336);
  gtk_widget_set_size_request (button26, 136, 29);

  button27 = gtk_button_new_with_mnemonic (_("Mes E-mails"));
  gtk_widget_show (button27);
  gtk_fixed_put (GTK_FIXED (fixed4), button27, 928, 384);
  gtk_widget_set_size_request (button27, 136, 29);

  image1 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_fixed_put (GTK_FIXED (fixed4), image1, 1056, 16);
  gtk_widget_set_size_request (image1, 40, 16);

  label22 = gtk_label_new (_("Recommended Trips "));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed4), label22, 424, 144);
  gtk_widget_set_size_request (label22, 196, 31);

  _ = gtk_label_new ("");
  gtk_widget_show (_);
  gtk_fixed_put (GTK_FIXED (fixed4), _, 0, 8);
  gtk_widget_set_size_request (_, 155, 51);

  entry15 = gtk_entry_new ();
  gtk_widget_show (entry15);
  gtk_fixed_put (GTK_FIXED (fixed4), entry15, 216, 0);
  gtk_widget_set_size_request (entry15, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry15), 8226);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window7, window7, "window7");
  GLADE_HOOKUP_OBJECT (window7, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window7, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (window7, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (window7, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (window7, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (window7, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (window7, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (window7, label20, "label20");
  GLADE_HOOKUP_OBJECT (window7, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (window7, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (window7, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (window7, label21, "label21");
  GLADE_HOOKUP_OBJECT (window7, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (window7, radiobutton5, "radiobutton5");
  GLADE_HOOKUP_OBJECT (window7, radiobutton6, "radiobutton6");
  GLADE_HOOKUP_OBJECT (window7, entry14, "entry14");
  GLADE_HOOKUP_OBJECT (window7, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (window7, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (window7, label26, "label26");
  GLADE_HOOKUP_OBJECT (window7, label27, "label27");
  GLADE_HOOKUP_OBJECT (window7, label31, "label31");
  GLADE_HOOKUP_OBJECT (window7, label30, "label30");
  GLADE_HOOKUP_OBJECT (window7, label34, "label34");
  GLADE_HOOKUP_OBJECT (window7, button29, "button29");
  GLADE_HOOKUP_OBJECT (window7, label29, "label29");
  GLADE_HOOKUP_OBJECT (window7, checkbutton4, "checkbutton4");
  GLADE_HOOKUP_OBJECT (window7, label24, "label24");
  GLADE_HOOKUP_OBJECT (window7, label32, "label32");
  GLADE_HOOKUP_OBJECT (window7, label33, "label33");
  GLADE_HOOKUP_OBJECT (window7, label28, "label28");
  GLADE_HOOKUP_OBJECT (window7, checkbutton3, "checkbutton3");
  GLADE_HOOKUP_OBJECT (window7, label25, "label25");
  GLADE_HOOKUP_OBJECT (window7, label35, "label35");
  GLADE_HOOKUP_OBJECT (window7, button30, "button30");
  GLADE_HOOKUP_OBJECT (window7, label17, "label17");
  GLADE_HOOKUP_OBJECT (window7, label15, "label15");
  GLADE_HOOKUP_OBJECT (window7, label18, "label18");
  GLADE_HOOKUP_OBJECT (window7, label19, "label19");
  GLADE_HOOKUP_OBJECT (window7, label16, "label16");
  GLADE_HOOKUP_OBJECT (window7, button25, "button25");
  GLADE_HOOKUP_OBJECT (window7, label23, "label23");
  GLADE_HOOKUP_OBJECT (window7, button26, "button26");
  GLADE_HOOKUP_OBJECT (window7, button27, "button27");
  GLADE_HOOKUP_OBJECT (window7, image1, "image1");
  GLADE_HOOKUP_OBJECT (window7, label22, "label22");
  GLADE_HOOKUP_OBJECT (window7, _, "_");
  GLADE_HOOKUP_OBJECT (window7, entry15, "entry15");

  return window7;
}

