/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window2 (void);
GtkWidget* create_fileselection1 (void);
GtkWidget* create_window5 (void);
GtkWidget* create_window7 (void);
